### ISSUE TITLE
Issue when importing gizeh

### ISSUE THREAD

**Issue by SamGRosen** [Zulko/gizeh#2]
When simply running:
import gizeh

I get the error:
Traceback (most recent call last):
  File "C:\Users\Sam\Documents\Python\python 2.7\animations.py", line 6, in <module>
    main()
  File "C:\Users\Sam\Documents\Python\python 2.7\animations.py", line 3, in main
    import gizeh
  File "build\bdist.win32\egg\gizeh__init__.py", line 5, in <module>
  File "build\bdist.win32\egg\gizeh\gizeh.py", line 4, in <module>
  File "build\bdist.win32\egg\cairocffi__init__.py", line 40, in <module>
  File "build\bdist.win32\egg\cairocffi__init__.py", line 34, in dlopen
  File "C:\Python27\lib\site-packages\cffi\api.py", line 118, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Python27\lib\site-packages\cffi\api.py", line 411, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Python27\lib\site-packages\cffi\api.py", line 400, in _load_backend_lib
    return backend.load_library(name, flags)
OSError: cannot load library libcairo.so.2: error 0x7e
I had a lot of difficulty installing due to some pip issues and had to install cairocffi, gizeh and numpy manually

**Comment by bzamecnik** [comment]
As said in: https://github.com/Kozea/WeasyPrint/issues/79#issuecomment-28835056:

```
$ export DYLD_FALLBACK_LIBRARY_PATH=/opt/local/lib
```

Works with macports and Python 3.4. Can be put into `~/.profile`.

**Comment by livethecode** [comment]
Hey I installed Cairo as mentioned in first reply. Still I am get error. Please help to resolve this error

Traceback (most recent call last):
  File "C:\Python34\vector.py", line 1, in <module>
    import gizeh
  File "C:\Python34\lib\site-packages\gizeh\__init__.py", line 5, in <module>
    from .gizeh import *
  File "C:\Python34\lib\site-packages\gizeh\gizeh.py", line 4, in <module>
    import cairocffi as cairo
  File "C:\Python34\lib\site-packages\cairocffi\__init__.py", line 46, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "C:\Python34\lib\site-packages\cairocffi\__init__.py", line 43, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2

**Comment by Jai-Singhal** [comment]
Hey I installed Cairo as mentioned in first reply. Still I am get error. Please help to resolve this error

Traceback (most recent call last):
File "C:\Python34\vector.py", line 1, in 
import gizeh
File "C:\Python34\lib\site-packages\gizeh__init__.py", line 5, in 
from .gizeh import *
File "C:\Python34\lib\site-packages\gizeh\gizeh.py", line 4, in 
import cairocffi as cairo
File "C:\Python34\lib\site-packages\cairocffi__init__.py", line 46, in 
cairo = dlopen(ffi, 'cairo', 'cairo-2')
File "C:\Python34\lib\site-packages\cairocffi__init__.py", line 43, in dlopen
raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2

**Comment by Myousri** [comment]
Here is what I have done to overcome this dlopen fail problem.

I installed the appropriate Pycairo executable whl from here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo
select the version that matches your python version, for example:
pycairo‑1.13.0‑cp27‑cp27m‑win32.whl is for python 2.7 32 bit architecture

After installing gizeh, I opened gizeh.py and replaced the following line:

"import cairocffi as cairo" with "import cairo"

I am not sure how dangerous this hack, I think @Zulko  who can better tell us. After this modification,
I made another change in pillowmulti.py by adding "quantizer=1" before line 333. Again, I am not sure how badly this affects the performance of gizeh.py. However, after these couple of changes, I was able to run the examples in the following link successfully and generate the corresponding images:
http://zulko.github.io/blog/2014/09/20/vector-animations-with-python/

In case things did not work with you, for your information, I am working on winpython 3.5 64 bit which can be installed from the following link:
https://winpython.github.io/

It is a portable python release for scientific and educational usage.

**Comment by JagritGumber** [comment]
> Here is what I have done to overcome this dlopen fail problem.
> 
> I installed the appropriate Pycairo executable whl from here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo select the version that matches your python version, for example: pycairo‑1.13.0‑cp27‑cp27m‑win32.whl is for python 2.7 32 bit architecture
> 
> After installing gizeh, I opened gizeh.py and replaced the following line:
> 
> "import cairocffi as cairo" with "import cairo"
> 
> I am not sure how dangerous this hack, I think @Zulko who can better tell us. After this modification, I made another change in pillowmulti.py by adding "quantizer=1" before line 333. Again, I am not sure how badly this affects the performance of gizeh.py. However, after these couple of changes, I was able to run the examples in the following link successfully and generate the corresponding images: http://zulko.github.io/blog/2014/09/20/vector-animations-with-python/
> 
> In case things did not work with you, for your information, I am working on winpython 3.5 64 bit which can be installed from the following link: https://winpython.github.io/
> 
> It is a portable python release for scientific and educational usage.

I am maybe a whole lot late for this, but I did the same I went to gizeh.py and made this line
`import cairocffi as cairo`
to be this 
`import cairo`

For some reason this just works, I wasn't able to install the thing in the first comment
